checkpoint: ''
data:
  eval:
    batch_size: 1
    dir: dataset/alphaimages_1k/test/images
    fov: 40.0
    n_view: 4
    pitch: 0.0
    r: 2.0
    yaw: 180
  train:
    batch_size: 1
    dir: dataset/alphaimages_1k/train/images
    fov_range:
    - 40.0
    - 40.0
    n_view: 1
    pitch_range:
    - -15.0
    - 45.0
    r_range:
    - 2.0
    - 2.0
    yaw_range:
    - 180.0
    - 180.0
eval_only: false
freq:
  eval: 5
  save:
    ckpt: 5
    visual: 2
guidance:
  edit_resolution: 1024
  flowedit:
    guidance_scale: 1.0
    n_max: 25
    n_min: 0
    noise_mode: velocity_fixed
    prompt: Generate a novel view
    seed: 0
    steps: 40
    true_cfg_scale_tgt: 15.0
  model_path: Qwen/Qwen-Image-Edit-2509
logdir: logs
lora:
  lora_rank: 32
mixed_precision: bf16
num_epochs: 500
pretrained:
  model: ./pretrained_weights/TRELLIS-image-large
reg:
  type: none
  weight_mode: uniform
renderer:
  bg_color:
  - 1.0
  - 1.0
  - 1.0
  far: 1.6
  near: 0.8
  resolution: 1024
  ssaa: 1
  type: gs
run_name: trellis_stage2_distill_reg_none_latent+ssim-02_lpips-02_max_25_velocity_fixed_norm
seed: 42
train:
  gradient_accumulation_steps: 4
  loss:
    latent_mse: 1.0
    lpips: 0.2
    reg: 1.0
    ssim: 0.2
  optimizer:
    beta1: 0.9
    beta2: 0.999
    eps: 0.0001
    lr: 3.0e-05
    type: adam
    weight_decay: 0.0001
